### ISSUE TITLE
Compatibility with Py3?

### ISSUE THREAD

**Issue by qlixed** [dnet/pysecstr#1]
As the Initialization module method change, this code don't run correctly on Py3.
If this project still alive, I can make the required changes and do a PR. But If you don't plan to maintan this anymore let me know I Just simply fork and continue my own business 😃

**Comment by dnet** [comment]
Thanks, I'll be happy to merge if you do a PR!

**Comment by qlixed** [comment]
Well, sorry but it's a ton of work make this available for dual usage, the extra code to write is large and I think that is better to make a separate project for this.
The changes in the codebase of the string/unicode in py3 is really big, more from py 3.3 onwards.
I still going to work in a spiritual sucessor of this for py3. If you want I can let you know where is published so we can crosslink the projects for people that need a py3 or py2 version of this functionality.

**Comment by dnet** [comment]
Sure, just let me know and I'll put a link into the README. Good luck!
